// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6nqFKWUcZ8YskqTa1qDq0SoMQckIxtxk',
    appId: '1:351910628918:web:49e11ca8fd180efd881297',
    messagingSenderId: '351910628918',
    projectId: 'banexcoin-6a811',
    authDomain: 'banexcoin-6a811.firebaseapp.com',
    storageBucket: 'banexcoin-6a811.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHy9vcJnZfP2o2MvU7WMsDAPX1T_0eQMs',
    appId: '1:351910628918:android:7da0d943057bb44d881297',
    messagingSenderId: '351910628918',
    projectId: 'banexcoin-6a811',
    storageBucket: 'banexcoin-6a811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABmd2Nr389fAdU-xbINfw_raXjHAZMHTY',
    appId: '1:351910628918:ios:0251ed2392bbbdea881297',
    messagingSenderId: '351910628918',
    projectId: 'banexcoin-6a811',
    storageBucket: 'banexcoin-6a811.firebasestorage.app',
    iosBundleId: 'com.example.banexcoin',
  );
}
